"""NotebookLM-style podcast generation for /reading-list max.

A "podcast" here is a manim video that visualizes:
- An audio waveform (the actual podcast audio would be generated separately
  by an audio model — this module focuses on the visual layer)
- Title card with the wiki's title
- Key concepts displayed as a typographic carousel
- A "talking points" section that cycles through the wiki's main ideas
- A credits card with sources

The manim-video skill provides the underlying animation primitives. This
module wraps it with the podcast-specific structure.

To use: call `build_podcast_script(wiki_path, item)` to generate the manim
Python script, then run it via the manim-video skill's workflow. The output
is an .mp4 file saved alongside the wiki.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


PODCAST_VISUAL_SCRIPT = '''\
"""
Auto-generated by sovth-config /reading-list max podcast.
Wiki: {wiki_path}
Source: {source}
"""

from manim import *


class {class_name}(Scene):
    def construct(self):
        # Title card
        title = Text(
            "{title}",
            font="Courier New",
            weight=BOLD,
            font_size=42,
        )
        title.to_edge(UP, buff=0.5)

        tagline = Text(
            "Reading List Podcast",
            font="Courier New",
            font_size=18,
        )
        tagline.next_to(title, DOWN, buff=0.3)

        self.play(Write(title), run_time=1.5)
        self.play(FadeIn(tagline, shift=UP), run_time=0.8)
        self.wait(1.0)

        # Audio waveform visual (placeholder — would be generated from real audio)
        waveform = self._build_waveform()
        self.play(Create(waveform), run_time=2.0)
        self.wait(2.0)

        # Key concepts carousel
{carousel_scenes}

        # Sources credits
        sources_text = Text(
            "Sources:\\n{sources_short}",
            font="Courier New",
            font_size=14,
            line_spacing=1.2,
        ).scale(0.7)
        self.play(FadeIn(sources_text, shift=UP), run_time=1.0)
        self.wait(3.0)

        # Outro
        outro = Text("TOWARDS SELF-IMPROVEMENT", font="Courier New", font_size=20)
        self.play(Write(outro), run_time=1.5)
        self.wait(2.0)

    def _build_waveform(self):
        import numpy as np
        np.random.seed(42)
        n = 200
        amplitudes = np.random.uniform(0.2, 1.0, n)
        bars = VGroup(*[
            Rectangle(width=0.04, height=a * 2, stroke_width=0)
                .set_fill(BLUE, opacity=a)
                .move_to([i * 0.05 - 5, 0, 0])
            for i, a in enumerate(amplitudes)
        ])
        return bars


{carousel_scenes_defs}
'''


def build_podcast_script(wiki_path: Path, item: dict[str, Any], key_concepts: list[str], sources: list[str]) -> str:
    """Generate the manim Python script for this item's podcast."""
    title = (item.get("title") or item.get("source") or "Untitled").replace('"', '\\"')
    class_name = "Podcast" + "".join(c for c in (item.get("id") or "Item") if c.isalnum()).title()
    sources_short = ", ".join(sources[:3]) if sources else "see wiki"
    carousel_scenes, carousel_defs = _carousel_scenes(key_concepts)
    return PODCAST_VISUAL_SCRIPT.format(
        wiki_path=str(wiki_path),
        source=item.get("source", ""),
        title=title,
        class_name=class_name,
        carousel_scenes=carousel_scenes,
        carousel_scenes_defs=carousel_defs,
        sources_short=sources_short.replace('"', '\\"'),
    )


def _carousel_scenes(concepts: list[str]) -> tuple[str, str]:
    """Generate manim code blocks for cycling through key concepts."""
    if not concepts:
        return ("        pass  # no concepts", "")
    blocks = []
    defs = []
    for i, concept in enumerate(concepts[:5]):
        concept_safe = concept[:60].replace('"', '\\"')
        method_name = f"_concept_{i+1}"
        def_code = f'''    def {method_name}(self):
        text = Text("{concept_safe}", font="Courier New", font_size=24)
        text.set_z_index(2)
        bg = Rectangle(width=12, height=2, fill_color=BLACK, fill_opacity=0.8, stroke_width=0)
        self.add(bg)
        self.play(Write(text), run_time=1.5)
        self.wait(2.0)
        self.play(FadeOut(text), run_time=0.5)
'''
        defs.append(def_code)
        blocks.append(f"        self.{method_name}()")
    return ("\n".join(blocks), "\n".join(defs))
